class RecipeData {
  String type;
  String image;
  String name;
  List ingredients;
  List howTo;

  RecipeData({
    required this.type,
    required this.image,
    required this.name,
    required this.ingredients,
    required this.howTo,
  });
}

var FoodDataContent = [
  // FOOD RECIPE
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
  RecipeData(
    type: "Food",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
];

var DrinkDataContent = [
  // DRINK RECIPE
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: 'Drink',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
];

var FavoriteDataContent = [
  // FAVORITE RECIPE
  RecipeData(
    type: 'Favorite',
    image: 'images/drink/wedang_jahe.jpg',
    name: "Wedang Jahe",
    ingredients: [
      "Jahe Potong secukupnya",
      "Gula Merah secukupnya",
      "Air secukupnya"
    ],
    howTo: [
      "1. Bakar jahe yang telah dibersihkan di atas arang atau kalau tidak ada bisa dibakar di atas kompor dengan api kecil.",
      "2. Pastikan jahe dibolak-balik hingga seluruh permukaan jahe terbakar dan mengeluarkan aroma khas.",
      "3. Sediakan gelas berukuran sedang, masukkan gula merah yang sudah dilelehkan sebanyak 2 sendok makan.",
      "4. Gepuk jahe yang sudah dibakar, kemudian masukkan ke dalam gelas.",
      "5. Tambahkan air panas, aduk hingga tercampur rata.",
      "6. Wedang Jahe bakar siap dihidangkan.",
    ],
  ),
  RecipeData(
    type: "Favorite",
    image: 'images/food/telur_balado.jpg',
    name: 'Telur Balado',
    ingredients: [
      "30 Butir Telur Rebus kupas",
      "2 Lonjor Petai kupas",
      "Minyak penumis bumbu",
      "Garam, Gula Pasir, Kaldu Jamur secukupnya",
      "18 Butir Bawang Merah",
      "12 Siung Bawang Putih",
      "3 Buah Tomat",
      "20 biji Cabai Rawit",
      "3 biji Cabai Merah Besar/Keriting",
      "1 sdt Merica Bubuk",
      "5 lembar daun jeruk buang tulang",
      "1 batang serai geprek",
      "lengkuas geprek",
      "jahe geprek",
      "2 sdm peres terasi goreng",
    ],
    howTo: [
      "1. Goreng telur rebus di minyak banyak dan panas sampai telur berkulit kecokelatan.",
      "2. Panaskan wajan, tuang minyak, tumis bumbu halus sampai layu.",
      "3. Masukkan bumbu cemplung tumis sampai wangi masukkan pete.",
      "4. Kemudian masukkan bahan lainnya, tes rasa.",
      "5. Terakhir masukkan telur yang sudah digoreng. Tumis sebentar agar bumbu meresap.",
      "6. Telor Balado siap disajikan."
    ],
  ),
];
